[bot]
application_id = ""
token = ""

[discord]
guild_id = ""
channels = ["", ""]

[out]
rss_items_limit = 10

# limited_feed_out_file = "./"
# full_feed_out_file = "./"

# > OPTIONAL (defaults to current working dir + {feedName}.rss)
# out_file_dir = "./dist" -> "./dist" equals "dist" and is relative path
# out_file_dir = "/dist" -> is absolute path